name: dart_rye
description: A Dart implementation of the Rye language
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  dart_console: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter

# Specify the entry point for the application
executables:
  dart_rye: dart_rye

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
