name: dart_rye
description: A Dart implementation of the Rye language evaluator
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter

# Specify the entry point for the application
executables:
  dart_rye: dart_rye

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
