# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        image:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Linux cgo dependancies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev # for webview https://github.com/webview/webview_go/blob/master/.github/workflows/ci.yaml
        sudo apt-get install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config # for ebitengine https://ebitengine.org/en/documents/install.html?os=linux#Debian_/_Ubuntu

    - name: Build
      # Enable all features for CI builds. 
      # TODO: add currently problematic tags: b_cayley,b_gtk,b_nng,b_qframe,b_raylib
      run: go build -v -tags "b_sqlite,b_http,b_sql,b_postgres,b_bson,b_crypto,b_smtpd,b_mail,b_bcrypt,b_telegram,b_html,b_contrib,b_openai,b_email,b_mail,b_mysql,b_nats,b_psql,b_psutil,b_sxml,b_echo,b_webview,b_ebitengine" -o bin/rye

    - name: Run Rye Tests
      run: cd tests ; ../bin/rye main.rye test
      timeout-minutes: 1

    - name: Build WASM
      run: |
        GOOS=js GOARCH=wasm go build -v -tags "b_tiny,b_norepl" -o wasm/rye.wasm main_wasm.go

#    - name: Test
#      run: go test -v -tags "b_tiny,b_sqlite,b_http,b_sql,b_postgres,b_openai,b_bson,b_crypto,b_smtpd,b_mail,b_postmark,b_bcrypt,b_telegram" ./...
