# .github/workflows/release.yml
name: goreleaser

on:
    push:
        tags:
          - 'v*.*.*'

permissions:
  contents: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      # issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needs full git history for changelog generation
          fetch-tags: true
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
